### ISSUE TITLE
Plugin "gulp-jpeg-xr" Error: spawn cat ENOENT

### ISSUE THREAD

**Issue by PeterIsaac-luftborn** [courtneypattison/gulp-jpeg-xr#1]
this is gulp file 
```
const gulp = require('gulp');
const debug = require("gulp-debug");
const jxr = require('gulp-jpeg-xr');

const convertJXR = () => {
	const src = [
		'images/**/*.{jpg,jpeg,png}',
		'images/*.{jpg,jpeg,png}',
	];
	return gulp.src(src)
		.pipe(jxr())
		.pipe(debug())
		.pipe(gulp.dest('images/compressed'))
		.pipe(debug())
		.on('error', (err) => {
			console.error(err);
		});
};
function defaultTask(cb) {
	convertJXR();
}
exports.default = defaultTask
```
but I get this error in console 
`Error in plugin "gulp-jpeg-xr"
Message:
    Error: spawn cat ENOENT`
![Screenshot_4](https://user-images.githubusercontent.com/48941798/57848302-cef03200-77d8-11e9-96e8-75295e85684c.png)

**Comment by courtneypattison** [comment]
Hey @luftbornDeveloper,

Thank you for reporting this issue! What OS are you using? I've only tested this plugin on macOS, so I'm not sure it works on other operating systems. Unfortunately nConvert cannot output JXR to STDOUT, so in the plugin I output it to a temporary file, then use the Unix utility `cat` to write to STDOUT so I can put the image into a buffer.

My guess is, you're running Windows and don't have `cat`. Based on this guess, I created a new version 1.0.3, that uses `type` instead of `cat` for Windows. I don't have a Windows machine, so I can't test that this fixes the problem.

Please let me know if this fix helps!

The problem could be a result of the way I'm creating the temporary file as well.

**Comment by PeterIsaac-luftborn** [comment]
Hey @courtneypattison 
thanks for response.
You guess right, I am using windows.
I've fixed it by using Cmder, it is "portable console emulator for Windows".
Unfortunately, the new release does not fix it.

**Comment by PeterIsaac-luftborn** [comment]
When I edited line 45 in index.js to be 
` const outputProcess = cp.spawn(outputProcessName, [tmpOutFilePath], { shell: true });`
it works in windows

**Comment by courtneypattison** [comment]
@luftbornDeveloper That is great! Thank you so much for looking into this issue. Would you like to submit a pull request with this change? I'd be happy to merge it. If not, I can add the fix. Thank you again :)

**Comment by PeterIsaac-luftborn** [comment]
Thank you, Please add the fix and test it on MacOS and Linux, I can tell you it works on Windows

**Comment by courtneypattison** [comment]
Sorry it took me so long to publish this fix! Thank you again for your help @luftbornDeveloper!
